unique_ids:
  assets:
    standard-page.html: 2BXMR7VA4ACIRZJORKDYEEXTEPVTEI37
    theme.css: LNGJCJYSMINSBIWNTPOWMIIV6CEAKH66
  forms:
    Form1: B2JDIFJEJBOPLXAY2GDULM72CHRMZHFH
  modules: {}
  scripts: {}
  server_modules: {}
